// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <C:/Users/pc/Documents/CRYENGINE Projects/fps test project/Code/GamePlugin.cpp>

